apiVersion: v1
kind: Service
metadata:
  name: trex-ui-service
  namespace: {{ .Values.Namespace }} 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trex-ui
